export enum ErrorMessages {
  USER_TOKEN_IS_INVALID = "USER_TOKEN_IS_INVALID",
  TODO_IS_NOT_FOUND = "TODO_IS_NOT_FOUND",
  NULL = '',
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
